

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.user;

import DAO.CoffeShopDAO;
import Model.Caffe;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.concurrent.ExecutionException;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author dwife
 */

public class User_InfoNgopi extends javax.swing.JFrame {


    private final Caffe caffeSedangDilihat;
    private final CoffeShopDAO dao = new CoffeShopDAO(); 

    public User_InfoNgopi(Caffe caffeDariDepan) {
        this.caffeSedangDilihat = caffeDariDepan;
        initComponents();
        setupUI();
        tampilkanDetail();
    }
    

    public User_InfoNgopi() {
        this.caffeSedangDilihat = null;
        initComponents();
        setupUI();
    }


    private void setupUI() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        

        jTextArea1.setEditable(false);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jTextArea1.setBorder(null);
        

        iconMaps.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn_BalikAhh.setCursor(new Cursor(Cursor.HAND_CURSOR));
        

        safeLoadIcon(iconMaps, "/image/Google Maps_2.png");
    }
    

    private void safeLoadIcon(JLabel label, String path) {
        try {
            URL url = getClass().getResource(path);
            if (url != null) {
                label.setIcon(new ImageIcon(url));
                label.setText("");
            } else {
                System.err.println("Warning: Gambar tidak ditemukan di " + path);
                label.setText("Maps");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void tampilkanDetail() {
        if (caffeSedangDilihat == null) return;
        lbNameCaffe.setText(caffeSedangDilihat.getNamaCaffe());
        this.setTitle("Info Ngopi: " + caffeSedangDilihat.getNamaCaffe());
        

        jTextArea1.setText(caffeSedangDilihat.getDeskripsi());
        jTextArea1.setCaretPosition(0);
        String alamat = caffeSedangDilihat.getAlamat(); 
        if (alamat == null || alamat.trim().isEmpty()) {
            alamat = "Alamat belum tersedia.";
        }
        
        txt_alamatlengkap.setText("<html><body style='width: 400px; color: white; font-family: Segoe UI; font-size: 14px;'>" + alamat + "</body></html>");
        

        loadGambarPenuh(caffeSedangDilihat.getId());
    }


    private void loadGambarPenuh(int idCaffe) {
        blGambar.setText("Memuat gambar...");
        blGambar.setIcon(null);
        blGambar.setHorizontalAlignment(SwingConstants.CENTER);
        
        new SwingWorker<ImageIcon, Void>() {
            @Override
            protected ImageIcon doInBackground() throws Exception {
                byte[] imgData = dao.getImageBytesById(idCaffe);
                if (imgData != null) {
                    Image img = ImageIO.read(new ByteArrayInputStream(imgData));
                    if (img != null) {
                        int targetW = blGambar.getWidth() > 0 ? blGambar.getWidth() : 600;
                        int targetH = blGambar.getHeight() > 0 ? blGambar.getHeight() : 400;
                        Image scaled = img.getScaledInstance(targetW, targetH, Image.SCALE_SMOOTH);
                        return new ImageIcon(scaled);
                    }
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    ImageIcon icon = get();
                    if (icon != null) {
                        blGambar.setText("");
                        blGambar.setIcon(icon);
                    } else {
                        blGambar.setText("Gambar tidak tersedia");
                    }
                } catch (InterruptedException | ExecutionException e) {
                    blGambar.setText("Gagal memuat gambar");
                }
            }
        }.execute();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbNameCaffe = new javax.swing.JLabel();
        pnGambar = new javax.swing.JPanel();
        blGambar = new javax.swing.JLabel();
        lbDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        iconMaps = new javax.swing.JLabel();
        txt_alamatlengkap = new javax.swing.JLabel();
        btn_BalikAhh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnDasar.setBackground(new java.awt.Color(9, 64, 49));
        pnDasar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnDasar.setPreferredSize(new java.awt.Dimension(1224, 700));

        jPanel1.setBackground(new java.awt.Color(9, 64, 49));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 208, 89), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        lbNameCaffe.setFont(new java.awt.Font("Segoe UI Black", 1, 56)); // NOI18N
        lbNameCaffe.setForeground(new java.awt.Color(255, 255, 255));
        lbNameCaffe.setText("NAMA CAFFE");

        blGambar.setText("gambar");

        javax.swing.GroupLayout pnGambarLayout = new javax.swing.GroupLayout(pnGambar);
        pnGambar.setLayout(pnGambarLayout);
        pnGambarLayout.setHorizontalGroup(
            pnGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGambarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnGambarLayout.setVerticalGroup(
            pnGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGambarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lbDeskripsi.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lbDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        lbDeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDeskripsi.setText("DESKRIPSI");
        lbDeskripsi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(9, 64, 49));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        iconMaps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Google Maps_2.png"))); // NOI18N
        iconMaps.setText("mps");
        iconMaps.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMaps.setIconTextGap(0);
        iconMaps.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconMaps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMapsMouseClicked(evt);
            }
        });

        txt_alamatlengkap.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txt_alamatlengkap.setForeground(new java.awt.Color(255, 255, 255));
        txt_alamatlengkap.setText("De Finibus Bonorum et Malorum");

        btn_BalikAhh.setBackground(new java.awt.Color(9, 64, 49));
        btn_BalikAhh.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btn_BalikAhh.setForeground(new java.awt.Color(255, 255, 255));
        btn_BalikAhh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back_1.png"))); // NOI18N
        btn_BalikAhh.setText("BACK");
        btn_BalikAhh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BalikAhhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(lbNameCaffe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(iconMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_alamatlengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_BalikAhh)
                        .addGap(39, 39, 39))
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(pnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbNameCaffe, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(lbDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(pnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txt_alamatlengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_BalikAhh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconMaps))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnDasar, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BalikAhhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BalikAhhActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_BalikAhhActionPerformed

    private void iconMapsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMapsMouseClicked
        // TODO add your handling code here:                                    
        // Logika Klik Icon Maps -> Buka Browser
        if (caffeSedangDilihat == null) return;
        
        String link = caffeSedangDilihat.getLinkMaps();
        
        if (link != null && !link.isEmpty()) {
            try {
                if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                    Desktop.getDesktop().browse(new URI(link));
                } else {
                    JOptionPane.showMessageDialog(this, "Browser otomatis tidak didukung di sistem ini.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal membuka link maps:\n" + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Link maps belum tersedia untuk kafe ini.");
        }
    
       

    }//GEN-LAST:event_iconMapsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_InfoNgopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_InfoNgopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_InfoNgopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_InfoNgopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_InfoNgopi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blGambar;
    private javax.swing.JButton btn_BalikAhh;
    private javax.swing.JLabel iconMaps;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbDeskripsi;
    private javax.swing.JLabel lbNameCaffe;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnGambar;
    private javax.swing.JLabel txt_alamatlengkap;
    // End of variables declaration//GEN-END:variables
}


