/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.Admin;

import Model.User;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author dwife
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());
    private User currentUser;

    /**
     * Creates new form DashboardAdmin
     */
    Color DefaultColor, ClikedColor;
    

    public DashboardAdmin(User user) {
        initComponents();
        this.currentUser = user;
        

        String welcomeMessage = "SELAMAT DATANG " + user.getUsername().toUpperCase() + " - ADMIN XSIRI COFFEE SHOP";
        jLabel1.setText(welcomeMessage);
        
        DefaultColor = new Color(9,64,49);
        ClikedColor = new Color (252,208,89);
        
 
        pCreate.setBackground(DefaultColor);
        pEdit.setBackground(DefaultColor);
        pInformation.setBackground(DefaultColor);
        

        logger.info("Admin dashboard opened for user: " + user.getUsername());
    }
    

    public DashboardAdmin() {
        initComponents();
        
        DefaultColor = new Color(9,64,49);
        ClikedColor = new Color (252,208,89);
        
        //set background color
        pCreate.setBackground(DefaultColor);
        pEdit.setBackground(DefaultColor);
        pInformation.setBackground(DefaultColor);
        
        // Default welcome message
        jLabel1.setText("SELAMAT DATANG ADMIN - XSIRI COFFEE SHOP");
    }


    public User getCurrentUser() {
        return currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMenuName = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMenu1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pEdit = new javax.swing.JPanel();
        txtEdit = new javax.swing.JLabel();
        pCreate = new javax.swing.JPanel();
        txtCreate2 = new javax.swing.JLabel();
        pInformation = new javax.swing.JPanel();
        txtdelete = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(252, 208, 89));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SELAMAT DATANG DI DASHBOARD ADMIN-INGPONGOPILURR");

        txtMenuName.setBackground(new java.awt.Color(9, 64, 49));
        txtMenuName.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtMenuName.setForeground(new java.awt.Color(255, 255, 255));
        txtMenuName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMenuName.setText("Menu");
        txtMenuName.setFocusable(false);

        close.setIcon(new javax.swing.ImageIcon("E:\\UAG\\Semester 3\\PBO\\UAS_NEW\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\src\\image\\Close.png")); // NOI18N
        close.setToolTipText("");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detail of Menu");

        txtMenu1.setBackground(new java.awt.Color(9, 64, 49));
        txtMenu1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtMenu1.setForeground(new java.awt.Color(255, 255, 255));
        txtMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMenu1.setIcon(new javax.swing.ImageIcon("E:\\UAG\\Semester 3\\PBO\\UAS_NEW\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\src\\image\\Menu.png")); // NOI18N
        txtMenu1.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtMenu1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMenuName)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(close)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMenuName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(txtMenu1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(9, 64, 49));

        pEdit.setBackground(new java.awt.Color(9, 64, 49));
        pEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEditMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEditMousePressed(evt);
            }
        });

        txtEdit.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEdit.setIcon(new javax.swing.ImageIcon("E:\\UAG\\Semester 3\\PBO\\UAS_NEW\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\src\\image\\Edit.png")); // NOI18N
        txtEdit.setText("Edit & Delete");
        txtEdit.setFocusable(false);

        javax.swing.GroupLayout pEditLayout = new javax.swing.GroupLayout(pEdit);
        pEdit.setLayout(pEditLayout);
        pEditLayout.setHorizontalGroup(
            pEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEdit)
                .addGap(34, 34, 34))
        );
        pEditLayout.setVerticalGroup(
            pEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEdit)
                .addContainerGap())
        );

        pCreate.setBackground(new java.awt.Color(9, 64, 49));
        pCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCreateMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pCreateMousePressed(evt);
            }
        });

        txtCreate2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtCreate2.setForeground(new java.awt.Color(255, 255, 255));
        txtCreate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCreate2.setIcon(new javax.swing.ImageIcon("E:\\UAG\\Semester 3\\PBO\\UAS_NEW\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\src\\image\\Plus.png")); // NOI18N
        txtCreate2.setText("Create");
        txtCreate2.setFocusable(false);
        txtCreate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCreate2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pCreateLayout = new javax.swing.GroupLayout(pCreate);
        pCreate.setLayout(pCreateLayout);
        pCreateLayout.setHorizontalGroup(
            pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCreate2)
                .addGap(36, 36, 36))
        );
        pCreateLayout.setVerticalGroup(
            pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCreateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCreate2))
        );

        pInformation.setBackground(new java.awt.Color(9, 64, 49));
        pInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pInformationMousePressed(evt);
            }
        });

        txtdelete.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        txtdelete.setForeground(new java.awt.Color(255, 255, 255));
        txtdelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdelete.setIcon(new javax.swing.ImageIcon("E:\\UAG\\Semester 3\\PBO\\UAS_NEW\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\APPS-REKOMENDASI-TEMPAT-NGOPI-master\\src\\image\\Delete.png")); // NOI18N
        txtdelete.setText("Informasion");
        txtdelete.setFocusable(false);

        javax.swing.GroupLayout pInformationLayout = new javax.swing.GroupLayout(pInformation);
        pInformation.setLayout(pInformationLayout);
        pInformationLayout.setHorizontalGroup(
            pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInformationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtdelete)
                .addGap(28, 28, 28))
        );
        pInformationLayout.setVerticalGroup(
            pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInformationLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(txtdelete))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(pCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(pEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInformationMousePressed
        // TODO add your handling code here:
        pCreate.setBackground(DefaultColor);
        pEdit.setBackground(DefaultColor);
        pInformation.setBackground(ClikedColor);
        
        txtMenuName.setText("Information");
    }//GEN-LAST:event_pInformationMousePressed

    private void pCreateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCreateMousePressed
        // TODO add your handling code here:
        pCreate.setBackground(ClikedColor);
        pEdit.setBackground(DefaultColor);
        pInformation.setBackground(DefaultColor);
        
        txtMenuName.setText("Create");
    }//GEN-LAST:event_pCreateMousePressed

    private void pEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEditMousePressed
        // TODO add your handling code here:
        pCreate.setBackground(DefaultColor);
        pEdit.setBackground(ClikedColor);
        pInformation.setBackground(DefaultColor);
        
        txtMenuName.setText("Edit");
    }//GEN-LAST:event_pEditMousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_closeMouseClicked

    private void txtCreate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCreate2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreate2MouseClicked

    private void pCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCreateMouseClicked
        // TODO add your handling code here:
        FCreateAdmin cr = new FCreateAdmin();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(cr).setVisible(true);
        
    }//GEN-LAST:event_pCreateMouseClicked

    private void pEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEditMouseClicked
        // TODO add your handling code here:
        FEditAdmin ed = new FEditAdmin();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(ed).setVisible(true);
    }//GEN-LAST:event_pEditMouseClicked

    private void pInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInformationMouseClicked
        // TODO add your handling code here:
        FInformationAdmin dl = new FInformationAdmin ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(dl).setVisible(true);
    }//GEN-LAST:event_pInformationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pCreate;
    private javax.swing.JPanel pEdit;
    private javax.swing.JPanel pInformation;
    private javax.swing.JLabel txtCreate2;
    private javax.swing.JLabel txtEdit;
    private javax.swing.JLabel txtMenu1;
    private javax.swing.JLabel txtMenuName;
    private javax.swing.JLabel txtdelete;
    // End of variables declaration//GEN-END:variables

    
}
