/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form.Admin;

import Config.DatabaseConnection;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import DAO.AdminCodeDAO;
import Model.Caffe;  
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author syafi
 */
public class FCreateAdmin extends javax.swing.JInternalFrame {
    
    private Integer id;
    private FEditAdmin parent;
    private AdminCodeDAO adao = new AdminCodeDAO();
    String path2 = null;

    /**
     * Creates new form FCreateAdmin
     */
    
    
    public FCreateAdmin() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }
    private void loadData() {
        Caffe cf = adao.getById(id);
        if (cf != null){
            txtFKategori.setText(cf.getKategori());
            txtFDaerah.setText(cf.getDaerah());
            txtFNama.setText(cf.getNamaCaffe());
            txtFDeskripsi.setText(cf.getDeskripsi());
            txtFAlamat.setText(cf.getAlamat());
            txtFLinkMaps.setText(cf.getLinkMaps());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JLabel();
        txtFKategori = new javax.swing.JTextField();
        txtFDaerah = new javax.swing.JTextField();
        txtDaerah = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtFNama = new javax.swing.JTextField();
        txtFDeskripsi = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JLabel();
        txtFAlamat = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JLabel();
        txtFLinkMaps = new javax.swing.JTextField();
        txtLinkMaps = new javax.swing.JLabel();
        txtUnggahFoto = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        lib_gambar = new javax.swing.JLabel();
        btnGambar = new javax.swing.JButton();
        t_imagePath = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(782, 614));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Caffe");

        txtKategori.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtKategori.setText("Kategori ");

        txtFKategori.addActionListener(this::txtFKategoriActionPerformed);

        txtFDaerah.addActionListener(this::txtFDaerahActionPerformed);

        txtDaerah.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtDaerah.setText("Daerah");

        txtNama.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtNama.setText("Nama ");

        txtFNama.addActionListener(this::txtFNamaActionPerformed);

        txtFDeskripsi.addActionListener(this::txtFDeskripsiActionPerformed);

        txtDeskripsi.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtDeskripsi.setText("Deskripsi");

        txtFAlamat.addActionListener(this::txtFAlamatActionPerformed);

        txtAlamat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtAlamat.setText("Alamat");

        txtFLinkMaps.addActionListener(this::txtFLinkMapsActionPerformed);

        txtLinkMaps.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtLinkMaps.setText("Link Maps");

        txtUnggahFoto.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtUnggahFoto.setText("Unggah Foto");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        lib_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGambar.setText("jButton1");
        btnGambar.addActionListener(this::btnGambarActionPerformed);

        t_imagePath.addActionListener(this::t_imagePathActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFDaerah))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFNama)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkMaps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(txtFAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFLinkMaps))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(txtUnggahFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lib_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKategori)
                            .addComponent(txtFKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDaerah)
                            .addComponent(txtFDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama)
                            .addComponent(txtFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeskripsi)
                            .addComponent(txtFDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat)
                            .addComponent(txtFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFLinkMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkMaps))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUnggahFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lib_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(270, 270, 270))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFKategoriActionPerformed

    private void txtFDaerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDaerahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDaerahActionPerformed

    private void txtFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNamaActionPerformed

    private void txtFDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDeskripsiActionPerformed

    private void txtFAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAlamatActionPerformed

    private void txtFLinkMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFLinkMapsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFLinkMapsActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Caffe cf = new Caffe();
        cf.setKategori(txtFKategori.getText());
        cf.setDaerah(txtFDaerah.getText());
        cf.setNamaCaffe(txtFNama.getText());
        cf.setDeskripsi(txtFDeskripsi.getText());
        cf.setAlamat(txtFAlamat.getText());
        cf.setLinkMaps(txtFLinkMaps.getText());
        cf.setImagePath(t_imagePath.getText());
        //String sql = "INSERT INTO caffe (kategori, daerah, namaCaffe, deskripsi, alamat, linkMaps, idPicture) VALUES (?, ?, ?, ?, ?, ?,?)";        
        
        
        boolean sukses;
    
        try {
            if (id == null) {
                // INSERT baru
                sukses = adao.insert(cf);
            } else {
                // UPDATE existing
                cf.setIdCaffe(id);
                sukses = adao.update(cf);
            }
        
            if (sukses) {
                // Clear form
                txtFKategori.setText("");
                txtFDaerah.setText("");
                txtFNama.setText("");
                txtFDeskripsi.setText("");
                txtFAlamat.setText("");
                txtFLinkMaps.setText("");
                lib_gambar.setIcon(null);
                path2 = null; // Reset path gambar

                JOptionPane.showMessageDialog(this, 
                    id == null ? "Data berhasil disimpan!" : "Data berhasil diupdate!");

                if (parent != null) {
                    parent.loadData(); // Refresh data di form utama
                }
                dispose(); // Tutup form

            } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data!");
            }    
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        } 
        
        
        
        /*
        try (Connection conn = DatabaseConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, cf.getKategori());
            ps.setString(2, cf.getDaerah());
            ps.setString(3, cf.getNamaCaffe());
            ps.setString(4, cf.getDeskripsi());
            ps.setString(5, cf.getAlamat());
            ps.setString(6, cf.getLinkMaps());
            InputStream is = new FileInputStream(new File(path2));
            ps.setBlob(7, is);
            ps.executeUpdate();
            txtFKategori.setText("");
            txtFDaerah.setText("");
            txtFNama.setText("");
            txtFDeskripsi.setText("");
            txtFAlamat.setText("");
            txtFLinkMaps.setText("");
            lib_gambar.setIcon(null);
            
            boolean sukses;
            if (id == null){
                sukses = adao.insert(cf);
            }else{
                cf.setIdCaffe(id);
                sukses = adao.insert(cf);
            }

            if (sukses){
                JOptionPane.showMessageDialog(this, "Data Berhasil disimpan!");
                parent.loadData();
                dispose();
            }else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan!");
            } 
            
            
            }catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            }*/
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void t_imagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_imagePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_imagePathActionPerformed

    private void btnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            t_imagePath.setText(path);
           
            try {
                //konversi blog gambar kedalam ke imageIcon
                byte[] img = Files.readAllBytes(selectedFile.toPath());
                ImageIcon imageIcon = new ImageIcon(img);
                
                // ukuran jlabel yang dinginkan 
                int labelWidth = 178;
                int labelHight = 177;
                
                // Ukuran gambar Asli
                int imageWidht = imageIcon.getIconWidth();
                int imageHight = imageIcon.getIconHeight();
                
                // Hitung Skala untuk ukuran gambar yang baru 
                double scaleX = (double) labelWidth / (double) imageWidht;
                double scaleY = (double) labelWidth / (double) imageWidht;
                double scale = Math.min (scaleX, scaleY);
                
                // ubah ukuran gambar dengan skala yang sudah dihitung 
                Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidht), (int) (scale * imageHight), Image.SCALE_SMOOTH);
                
                //Tampilkan imageICon pada Jlabel
                lib_gambar.setIcon(new ImageIcon (scaledImage));
                path2 = path;
            } catch (IOException ex){
                ex.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_btnGambarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnGambar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lib_gambar;
    private javax.swing.JTextField t_imagePath;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtDaerah;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JTextField txtFAlamat;
    private javax.swing.JTextField txtFDaerah;
    private javax.swing.JTextField txtFDeskripsi;
    private javax.swing.JTextField txtFKategori;
    private javax.swing.JTextField txtFLinkMaps;
    private javax.swing.JTextField txtFNama;
    private javax.swing.JLabel txtKategori;
    private javax.swing.JLabel txtLinkMaps;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtUnggahFoto;
    // End of variables declaration//GEN-END:variables
}
