/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form.Admin;

import Config.DatabaseConnection;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import DAO.AdminCodeDAO;
import Model.Caffe;  
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author syafi
 */
public class FCreateAdmin extends javax.swing.JInternalFrame {
    
    private Integer id;
    private FEditAdmin parent;
    private AdminCodeDAO adao = new AdminCodeDAO();
    String path2 = null;

    /**
     * Creates new form FCreateAdmin
     */
    
    
    public FCreateAdmin() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }
    
    public FCreateAdmin(FEditAdmin parent, Integer id) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.parent = parent;
        this.id = id;
        if(id != null){
            setTitle("Ubah caffe");
            loadData();
        }
    }
    
    private void loadData() {
        Caffe cf = adao.getById(id);
        if (cf != null){
            txtFKategori.setText(cf.getKategori());
            txtFDaerah.setText(cf.getDaerah());
            txtFNama.setText(cf.getNamaCaffe());
            txtFDeskripsi.setText(cf.getDeskripsi());
            txtFAlamat.setText(cf.getAlamat());
            txtFLinkMaps.setText(cf.getLinkMaps());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JLabel();
        txtFKategori = new javax.swing.JTextField();
        txtFDaerah = new javax.swing.JTextField();
        txtDaerah = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtFNama = new javax.swing.JTextField();
        txtFDeskripsi = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JLabel();
        txtFAlamat = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JLabel();
        txtFLinkMaps = new javax.swing.JTextField();
        txtLinkMaps = new javax.swing.JLabel();
        txtUnggahFoto = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        lib_gambar = new javax.swing.JLabel();
        btnGambar = new javax.swing.JButton();
        t_imagePath = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1100, 614));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 614));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Caffe");

        txtKategori.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtKategori.setText("Kategori ");

        txtFKategori.addActionListener(this::txtFKategoriActionPerformed);

        txtFDaerah.addActionListener(this::txtFDaerahActionPerformed);

        txtDaerah.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtDaerah.setText("Daerah");

        txtNama.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtNama.setText("Nama ");

        txtFNama.addActionListener(this::txtFNamaActionPerformed);

        txtFDeskripsi.addActionListener(this::txtFDeskripsiActionPerformed);

        txtDeskripsi.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtDeskripsi.setText("Deskripsi");

        txtFAlamat.addActionListener(this::txtFAlamatActionPerformed);

        txtAlamat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtAlamat.setText("Alamat");

        txtFLinkMaps.addActionListener(this::txtFLinkMapsActionPerformed);

        txtLinkMaps.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtLinkMaps.setText("Link Maps");

        txtUnggahFoto.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        txtUnggahFoto.setText("Unggah Foto");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        lib_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGambar.setBackground(new java.awt.Color(255, 153, 153));
        btnGambar.setText("UP");
        btnGambar.addActionListener(this::btnGambarActionPerformed);

        t_imagePath.addActionListener(this::t_imagePathActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkMaps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(txtFDaerah)
                    .addComponent(txtFNama)
                    .addComponent(txtFDeskripsi)
                    .addComponent(txtFAlamat)
                    .addComponent(txtFLinkMaps))
                .addGap(169, 169, 169)
                .addComponent(txtUnggahFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lib_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel1)))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKategori)
                            .addComponent(txtFKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDaerah)
                            .addComponent(txtFDaerah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama)
                            .addComponent(txtFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeskripsi)
                            .addComponent(txtFDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat)
                            .addComponent(txtFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinkMaps)
                            .addComponent(txtFLinkMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUnggahFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lib_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(270, 270, 270))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFKategoriActionPerformed

    private void txtFDaerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDaerahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDaerahActionPerformed

    private void txtFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNamaActionPerformed

    private void txtFDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDeskripsiActionPerformed

    private void txtFAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAlamatActionPerformed

    private void txtFLinkMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFLinkMapsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFLinkMapsActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
            // TODO add your handling code here:
       if (txtFKategori.getText().trim().isEmpty() ||
            txtFDaerah.getText().trim().isEmpty() ||
            txtFNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Kategori, Daerah, dan Nama harus diisi!", 
                "Validasi Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Caffe cf = new Caffe();
            cf.setKategori(txtFKategori.getText());
            cf.setDaerah(txtFDaerah.getText());
            cf.setNamaCaffe(txtFNama.getText());
            cf.setDeskripsi(txtFDeskripsi.getText());
            cf.setAlamat(txtFAlamat.getText());
            cf.setLinkMaps(txtFLinkMaps.getText());

       
            if (imageBytes != null && imageBytes.length > 0) {
              
                cf.setGambarStream(new java.io.ByteArrayInputStream(imageBytes));
            } else if (t_imagePath.getText() != null && !t_imagePath.getText().trim().isEmpty()) {
           
                File file = new File(t_imagePath.getText());
                if (file.exists() && file.canRead()) {
                    cf.setImagePath(t_imagePath.getText());
                }
            }

            boolean sukses;

            if (id == null) {
             
                sukses = adao.insert(cf);
            } else {
           
                cf.setId(id);
                sukses = adao.update(cf);
            }

            if (sukses) {
           
                resetForm();

                JOptionPane.showMessageDialog(this, 
                    id == null ? "Data berhasil disimpan!" : "Data berhasil diupdate!");

                if (parent != null) {
                    parent.loadData();
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Gagal menyimpan data! Periksa koneksi database atau ukuran file.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void resetForm() {
        txtFKategori.setText("");
        txtFDaerah.setText("");
        txtFNama.setText("");
        txtFDeskripsi.setText("");
        txtFAlamat.setText("");
        txtFLinkMaps.setText("");
        t_imagePath.setText("");
        lib_gambar.setIcon(null);
        lib_gambar.setText("No Image");
        path2 = null;
        imageBytes = null;
        id = null;
         
    }//GEN-LAST:event_btnSimpanActionPerformed
    private byte[] imageBytes = null;
    
    
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void t_imagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_imagePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_imagePathActionPerformed

    private void btnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambarActionPerformed
        // TODO add your handling code here:
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "jpeg", "gif", "png");
    fileChooser.addChoosableFileFilter(filter);
    int result = fileChooser.showOpenDialog(this);
    
    if(result == JFileChooser.APPROVE_OPTION){
        File selectedFile = fileChooser.getSelectedFile();
        String path = selectedFile.getAbsolutePath();
        t_imagePath.setText(path);
       
        try {

            imageBytes = Files.readAllBytes(selectedFile.toPath());
            
    
            if (imageBytes.length > 16 * 1024 * 1024) {
                JOptionPane.showMessageDialog(this, 
                    "File terlalu besar! Maksimal 16MB. Ukuran file: " + 
                    (imageBytes.length / (1024 * 1024)) + "MB");
                imageBytes = null;
                return;
            }

            ImageIcon imageIcon = new ImageIcon(imageBytes);
            

            int labelWidth = lib_gambar.getWidth();
            int labelHeight = lib_gambar.getHeight();
            
            if (labelWidth <= 0) labelWidth = 178;
            if (labelHeight <= 0) labelHeight = 177;
            
  
            Image scaledImage = imageIcon.getImage().getScaledInstance(
                labelWidth, labelHeight, Image.SCALE_SMOOTH);
            
            lib_gambar.setIcon(new ImageIcon(scaledImage));
            path2 = path;
            
        } catch (IOException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error membaca file: " + ex.getMessage());
            imageBytes = null;
        } catch (OutOfMemoryError e) {
            JOptionPane.showMessageDialog(this, "File terlalu besar untuk diproses!");
            imageBytes = null;
        }
     }
    }//GEN-LAST:event_btnGambarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnGambar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lib_gambar;
    private javax.swing.JTextField t_imagePath;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtDaerah;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JTextField txtFAlamat;
    private javax.swing.JTextField txtFDaerah;
    private javax.swing.JTextField txtFDeskripsi;
    private javax.swing.JTextField txtFKategori;
    private javax.swing.JTextField txtFLinkMaps;
    private javax.swing.JTextField txtFNama;
    private javax.swing.JLabel txtKategori;
    private javax.swing.JLabel txtLinkMaps;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtUnggahFoto;
    // End of variables declaration//GEN-END:variables
}


